version: '3'
services:
  app1:
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    ports:
    - "8081:8080"
    restart: unless-stopped
  app2:
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M

    ports:
    - "8082:8080"
    restart: unless-stopped
  app3:
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    ports:
    - "8083:8080"
    restart: unless-stopped
  app4:
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    ports:
    - "8084:8080"
    restart: unless-stopped
  app5:
    build: .
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    ports:
    - "8085:8080"
    restart: unless-stopped
  nginx:
    build: ./infra/nginx
    ports:
    - "8080:80"
    depends_on:
    - app1
    - app2